[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Align Tool"
description="Quickly align objects"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"
icon = "data/icon-align.png"

preview_image = "data/preview-align.png"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Tool"

# Keywords for the extension
keywords = ["tool", "align", "transform", "scale", "match", "rotate"]

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.ui" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.popup_dialog" = {}

# Main python module this extension provides, it will be publicly available as "import omni.kit.property.align".
[[python.module]]
name = "ov.tools.align"
