[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Align Tool"
description="The simplest python extension example. Use it as a starting point for your extensions."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Align"

# Keywords for the extension
keywords = ["kit", "align"]

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.ui" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.popup_dialog" = {}

# Main python module this extension provides, it will be publicly available as "import omni.kit.property.align".
[[python.module]]
name = "omni.kit.property.align"
